src/main/java/org/mintcode/errabbit/controller/console/EventController.java
package org.mintcode.errabbit.controller.console;

import org.apache.commons.lang3.StringUtils;
import org.mintcode.errabbit.core.eventstream.EventStreamCentral;
import org.mintcode.errabbit.core.eventstream.event.EventCondition;
import org.mintcode.errabbit.core.eventstream.event.EventMapping;
import org.mintcode.errabbit.core.eventstream.event.EventMappingRepository;
import org.mintcode.errabbit.core.eventstream.event.action.EventAction;
import org.mintcode.errabbit.core.eventstream.event.action.EventActionRepository;
import org.mintcode.errabbit.core.rabbit.managing.RabbitManagingService;
import org.mintcode.errabbit.core.rabbit.name.RabbitCache;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created by soleaf on 1/8/16.
 */
@Controller
@RequestMapping(value = "/event")
public class EventController {

    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    @Autowired
    private EventActionRepository eventActionRepository;

    @Autowired
    private EventMappingRepository eventMappingRepository;

    @Autowired
    private RabbitCache rabbitCache;

    @Autowired
    private RabbitManagingService rabbitManagingService;

    @Autowired
    private EventStreamCentral eventStreamCentral;

    @RequestMapping(value = "mapping/list")
    public ModelAndView mappingList(Model model) {
        model.addAttribute("list", eventMappingRepository.findAll());
        return new ModelAndView("event/mapping_list");
    }

    @RequestMapping(value = "mapping/add")
    public ModelAndView mappingAdd(Model model) {
        // Rabbit list
        model.addAttribute("groups", rabbitManagingService.
                getRabbitGroupWithRabbitSorted(rabbitManagingService.getRabbitsByGroup(rabbitCache.getRabbits())));
        model.addAttribute("title", "New mapping");
        model.addAttribute("action", "/event/mapping/add_action.err");
        return new ModelAndView("event/mapping_form");
    }

    @RequestMapping(value = "mapping/modify")
    public String mappingModify(Model model, @RequestParam String id, RedirectAttributes redirectAttrs) {

        try{
            EventMapping mapping = eventMappingRepository.findOne(id);
            if (mapping == null){
                throw new NullPointerException("Not found mapping");
            }

            // Rabbit list
            model.addAttribute("groups", rabbitManagingService.
                    getRabbitGroupWithRabbitSorted(rabbitManagingService.getRabbitsByGroup(rabbitCache.getRabbits())));
            model.addAttribute("title", "Modify mapping");
            model.addAttribute("action", "/event/mapping/add_action.err");
            model.addAttribute("mapping", mapping);

            if (!mapping.getCondition().getRabbitIdSet().isEmpty()){
                model.addAttribute("rabbitIdSet", StringUtils.join(mapping.getCondition().getRabbitIdSet(),","));
            }
            return "event/mapping_form";
        }
        catch (Exception e){
            redirectAttrs.addAttribute("error", e.getMessage());
            return "redirect:/event/mapping/list.err";
        }
    }

    @RequestMapping(value = "mapping/add_action")
    public String mappingAddAction(Model model,
                                   @RequestParam(required = true) String name,
                                   @RequestParam(required = true) String rabbitSet,
                                   @RequestParam(required = true) String level,
                                   @RequestParam(required = false) String matchClass,
                                   @RequestParam(required = false) String message,
                                   @RequestParam(required = true) Integer thresholdCount,
                                   @RequestParam(required = true) Integer period,
                                   @RequestParam(required = true) Integer sleep,
                                   @RequestParam(required = false, defaultValue = "False") Boolean active,
                                   @RequestParam(required = false, defaultValue = "False") Boolean exception,
                                   @RequestParam(required = false) String id,
                                   RedirectAttributes redirectAttrs
    ) {

        try{
            EventMapping mapping;
            EventCondition condition;
            if (id == null){
                mapping = new EventMapping();
                condition = new EventCondition();
            }
            else{
                mapping = eventMappingRepository.findOne(id);
                if (id == null){
                    throw new NullPointerException("Not found mapping");
                }
                condition = mapping.getCondition();
            }

            String[] arr = rabbitSet.split(",");
            for (String rabbitId : arr) {
                condition.getRabbitIdSet().clear();
                condition.addRabbitId(rabbitId);
            }
            condition.setMatchLevel(level);
            if (matchClass.length() > 0) {
                condition.setMatchClass(matchClass);
            }
            if (message.length() > 0) {
                condition.setIncludeMessage(message);
            }
            condition.setThresholdCount(thresholdCount);
            condition.setPeriodSec(period);
            condition.setSleepSecAfterAction(sleep);
            condition.setHasException(exception);
            mapping.setName(name);
            mapping.setActive(active);
            mapping.setCondition(condition);

            if (id == null){
                eventMappingRepository.insert(mapping);
                redirectAttrs.addAttribute("info", "Success creating new mapping");
            }
            else{
                eventMappingRepository.save(mapping);
                redirectAttrs.addAttribute("info", "Success modifying mapping");
            }

            return "redirect:/event/mapping/list.err";
        }
        catch (Exception e){
            redirectAttrs.addAttribute("error", e.getMessage());
            return "redirect:/event/mapping/list.err";
        }

    }

    @RequestMapping(value = "mapping/delete")
    public String mappingDelete(Model model,
                                   @RequestParam(required = false) String id,
                                RedirectAttributes redirectAttrs
    ) {

        try{
            EventMapping mapping = eventMappingRepository.findOne(id);
            if (id == null){
                throw new NullPointerException("Not found mapping");
            }
            eventMappingRepository.delete(mapping);
            redirectAttrs.addAttribute("info","success to delete mapping");
            return "redirect:/event/mapping/list.err";
        }
        catch (Exception e){
            redirectAttrs.addAttribute("error", e.getMessage());
            return "redirect:/event/mapping/list.err";
        }

    }

    @RequestMapping(value = "mapping/action")
    public String mappingAction(Model model, @RequestParam String id, RedirectAttributes redirectAttrs){
        try{
            EventMapping mapping = eventMappingRepository.findOne(id);
            if (mapping == null){
                throw new NullPointerException("Can't find mapping for id:"+id);
            }

            List<EventAction> allActions = eventActionRepository.findAll();
            List<EventAction> avaliableActions = new ArrayList<>();
            if (!allActions.isEmpty()){
                for (EventAction action : allActions){
                    if (!mapping.getActions().contains(action)){
                        avaliableActions.add(action);
                    }
                }
            }

            model.addAttribute("mapping", mapping);
            model.addAttribute("hasActions", mapping.getActions());
            model.addAttribute("allActions", avaliableActions);
            model.addAttribute("action", "action_action.err");
        }
        catch (Exception e){
            redirectAttrs.addAttribute("error",e.getMessage());
            return "redirect:/event/mapping/list.err";
        }
        finally {
            return "event/mapping_action";
        }
    }

    @RequestMapping(value = "mapping/action_action")
    public String mappingActionAction(Model model,
                                            @RequestParam String id,
                                            @RequestParam String actions,
                                      RedirectAttributes redirectAttrs){
        try{
            EventMapping mapping = eventMappingRepository.findOne(id);
            if (mapping == null){
                throw new NullPointerException("Can't find mapping for id:"+id);
            }

            // Clear
            mapping.getActions().clear();

            // Add or modify
            if (actions.length() > 0){
                String[] actionArr = actions.split(",");
                for (String actionId : actionArr){
                    EventAction action = eventActionRepository.findOne(actionId);
                    if (action == null){
                        throw new NullPointerException("Can't find action for id:"+actionId);
                    }
                    mapping.getActions().add(action);
                }
            }

            // Save
            eventMappingRepository.save(mapping);
            redirectAttrs.addAttribute("info", "Success modifying mapping action");
            return "redirect:/event/mapping/list.err";
        }

src/main/java/org/mintcode/errabbit/core/eventstream/event/action/AbstractEventAction.java
package org.mintcode.errabbit.core.eventstream.event.action;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.util.StringUtils;

import java.util.Map;

/**
 * Created by soleaf on 12/31/15.
 */
public abstract class AbstractEventAction implements EventAction {

    @Id
    String id;

    private String name;

    @Transient
    protected String errorMessage = null;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public void validationUISetting(Map<String, String> dataSet) throws InvalidEventActionUISettingValueException {
        if (!StringUtils.hasLength(dataSet.get("name"))){
            throw new InvalidEventActionUISettingValueException("invalid value for name");
        }
    }

    public void settingFromUI(Map<String, String> dataSet) throws InvalidEventActionUISettingValueException {
        name = dataSet.get("name");
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "AbstractEventAction{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", errorMessage='" + errorMessage + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AbstractEventAction that = (AbstractEventAction) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        return name != null ? name.equals(that.name) : that.name == null;

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}

src/main/java/org/mintcode/errabbit/core/eventstream/event/action/EventAction.java
package org.mintcode.errabbit.core.eventstream.event.action;

import org.mintcode.errabbit.core.eventstream.event.EventCondition;
import org.mintcode.errabbit.model.Log;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;
import java.util.Map;

/**
 * Created by soleaf on 12/31/15.
 */
@Document(collection = "event.action")
public interface EventAction{

    public String getId();
    public void setId(String id);

    /**
     * Run action
     * @param eventCondition
     * @param log
     * @return
     */
    public Boolean run(EventCondition eventCondition, Log log);

    /**
     * Copy action instance to run on eventstream
     * @return
     */
    public EventAction copy();

    /**
     * Get label made by user
     * @return
     */
    public String getName();
    public void setName(String name);

    /**
     * Get description for ui
     * @return
     */
    public String getDescription();

    /**
     * Identity type name (className)
     * @return
     */
    public String getTypeName();

    /**
     * Get occurred error message in run
     * @return null or error message string
     */
    public String getErrorMessage();

    /**
     * Defined setting UI elements
     * @return
     */
    public List<EventActionUIElement> getUIElements();

    /**
     * Check setting key/value is valid
     * @param dataSet
     * @return
     */
    public void validationUISetting(Map<String,String> dataSet) throws InvalidEventActionUISettingValueException;

    /**
     * Apply setting key/value
     * @param dataSet
     */
    public void settingFromUI(Map<String,String> dataSet) throws InvalidEventActionUISettingValueException;

}

src/main/java/org/mintcode/errabbit/core/eventstream/event/action/NotificationEventAction.java
package org.mintcode.errabbit.core.eventstream.event.action;

import org.mintcode.errabbit.core.eventstream.event.EventCondition;
import org.mintcode.errabbit.model.Log;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;
import java.util.Map;

/**
 * Created by soleaf on 12/31/15.
 */
@Document(collection = "event.action")
public class NotificationEventAction extends AbstractEventAction {

    @Override
    public Boolean run(EventCondition eventCondition, Log log) {
        return true;
    }

    @Override
    public EventAction copy() {
        return null;
    }

    @Override
    public String getDescription() {
        return "NotificationEventAction";
    }

    public String getTypeName() {
        return getClass().getSimpleName();
    }

    @Override
    public List<EventActionUIElement> getUIElements() {
        return null;
    }

    @Override
    public void validationUISetting(Map<String, String> dataSet) {

    }

    @Override
    public void settingFromUI(Map<String, String> dataSet) {

    }
}

src/main/webapp/WEB-INF/jsp/event/action_form.jsp
<%--
  Created by IntelliJ IDEA.
  User: soleaf
  Date: 15. 8. 9.
  Time: 오후 5:30
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<html>
<head>
    <jsp:include page="../common/header_include.jsp"/>
    <link rel="stylesheet" href="/css/event.css" type="text/css"/>
    <script src="/js/event.js"></script>
</head>
<body class="event">
<jsp:include page="../common/nav.jsp">
    <jsp:param name="event" value="active"/>
</jsp:include>
<section class="page">
    <jsp:include page="side.jsp">
        <jsp:param name="action" value="active"/>
    </jsp:include>
    <div class="page-side-margin">
        <h3>${title}</h3>
        <p>${desc}</p>
        <div class="form-horizontal event-form">
            <form class="form" action="${action}">
                <input type="hidden" name="className" value="${param.actionClassName}"/>
                <c:if test="${not empty eaction}">
                    <input type="hidden" name="id" value="${eaction.id}"/>
                </c:if>
                <div class="main-form">
                    <label class="control-label">GENERAL</label>
                    <div class="sub-form">
                        <label for="name" class="control-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name"
                                value="${eaction.name}">
                        <span class="help-block">Just name for identifying</span>
                    </div>
                </div>

                <div class="main-form">
                    <label class="control-label">OPTION</label>
                    <c:forEach var="item" items="${uiElements}">
                        <div class="sub-form">
                            <label class="control-label">${item.label}</label>
                            <input type="${item.valueType}" class="form-control" name="${item.name}"
                                   placeholder="${item.defaultValue}" value="${item.value}"/>
                            <span class="help-block">${item.help}</span>
                        </div>
                    </c:forEach>
                </div>

                <c:if test="${not empty e}">
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <strong>ERROR</strong> ${e.message}
                    </div>
                </c:if>
                <div class="form_submit">
                    <button type="submit"s class="btn btn-primary">CONFIRM</button>
                    <button class="btn btn-default">CANCEL</button>
                </div>
            </form>
        </div>
    </div>
</section>
<jsp:include page="../common/footer.jsp"/>
</body>
</html>

src/main/webapp/WEB-INF/jsp/event/action_list.jsp
<%--
  Created by IntelliJ IDEA.
  User: soleaf
  Date: 15. 8. 9.
  Time: 오후 5:30
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<html>
<head>
    <jsp:include page="../common/header_include.jsp"/>
    <link rel="stylesheet" href="/css/event.css" type="text/css"/>
    <script src="/js/event.js"></script>
</head>
<body class="event">
<jsp:include page="../common/nav.jsp">
    <jsp:param name="event" value="active"/>
</jsp:include>
<section class="page">
    <jsp:include page="side.jsp">
        <jsp:param name="action" value="active"/>
    </jsp:include>
    <div class="page-side-margin">
        <div class="page-information">
            <h3>Event Action</h3>
            <p class="desc">
                You can make event actions to link to event mapping.
            </p>
            <div class="btn-group">
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        New Action <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="add.err?actionClassName=org.mintcode.errabbit.core.eventstream.event.action.SlackNotificationEventAction">Send Slack</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="alertbox">
            <c:if test="${not empty param.info}">
                <div class="alert alert-success" role="alert">${param.info}</div>
            </c:if>

            <c:if test="${not empty param.error}">
                <div class="alert alert-danger" role="alert">${param.error}</div>
            </c:if>
        </div>

        <c:if test="${not empty list}">
        <table class="table table-striped action-table">
            <thead>
                <th width="200px">Name</th>
                <th>Type</th>
                <th width="130px">Managing</th>
            </thead>
            <tbody>
            <c:forEach items="${list}" var="item">
                <tr>
                    <td>${item.name}</td>
                    <td>${item.typeName}</td>
                    <td>
                        <div class="btn-group" role="group">
                        <a href="modify.err?id=${item.id}" role="button" class="btn btn-default btn-xs">modify</a>
                        <a href="delete.err?id=${item.id}" role="button" class="btn btn-default btn-xs">delete</a>
                        </div>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
        </c:if>
    </div>
</section>
<jsp:include page="../common/footer.jsp"/>
</body>
</html>

src/main/webapp/WEB-INF/jsp/event/mapping_action.jsp
<%--
  Created by IntelliJ IDEA.
  User: soleaf
  Date: 15. 8. 9.
  Time: 오후 5:30
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<html>
<head>
    <jsp:include page="../common/header_include.jsp"/>
    <link rel="stylesheet" href="/css/event.css" type="text/css"/>
    <script src="/js/event.mapping.action.js"></script>
</head>
<body class="event">
<jsp:include page="../common/nav.jsp">
    <jsp:param name="event" value="active"/>
</jsp:include>
<section class="page">
    <jsp:include page="side.jsp">
        <jsp:param name="mapping" value="active"/>
    </jsp:include>
    <div class="page-side-margin">
        <h3>EventMapping Actions</h3>
        <p>name: ${mapping.name}</p>
        <p>id: ${mapping.id}</p>
        <div class="form-horizontal event-form">
            <div class="panel panel-primary">
                <div class="panel-heading">Linked actions</div>
                <ul id="linkedActions" class="list-group">
                    <c:if test="${not empty hasActions}">
                        <c:forEach items="${hasActions}" var="action">
                            <a class="list-group-item" role="button"
                               data-id="${action.id}">${action.name} <small>(${action.typeName})</small></a>
                        </c:forEach>
                    </c:if>
                </ul>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Avaliable actions</div>
                <ul id="allActions" class="list-group">
                    <c:if test="${not empty allActions}">
                        <c:forEach items="${allActions}" var="action">
                            <a class="list-group-item" role="button"
                               data-id="${action.id}">${action.name} <small>(${action.typeName})</small></a>
                        </c:forEach>
                    </c:if>
                </ul>
            </div>
            <form id="submit" action="${action}">
                <input id="input-linkedActions" name="actions" type="hidden"/>
                <input name="id" type="hidden" value="${mapping.id}"/>
                <div class="form_submit">
                    <button type="submit" s class="btn btn-primary">CONFIRM</button>
                    <button class="btn btn-default">CANCEL</button>
                </div>
            </form>
        </div>
    </div>
</section>
<jsp:include page="../common/footer.jsp"/>
</body>
</html>

src/main/webapp/WEB-INF/jsp/event/mapping_list.jsp
<%--
  Created by IntelliJ IDEA.
  User: soleaf
  Date: 15. 8. 9.
  Time: 오후 5:30
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<html>
<head>
    <jsp:include page="../common/header_include.jsp"/>
    <link rel="stylesheet" href="/css/event.css" type="text/css"/>
    <script src="/js/event.js"></script>
</head>
<body class="event">
<jsp:include page="../common/nav.jsp">
    <jsp:param name="event" value="active"/>
</jsp:include>
<section class="page">
    <jsp:include page="side.jsp">
        <jsp:param name="mapping" value="active"/>
    </jsp:include>
    <div class="page-side-margin">
        <div class="page-information">
            <h3>Event Mapping</h3>
            <p class="desc">
                Event Mapping is defining about event condition and link to actions.
                <br/>You can create event mapping and add action.
            </p>
            <div class="btn-group">
                <a type="button" role="button" class="btn btn-default btn-sm" href="add.err">New Mapping
                </a>
            </div>
        </div>
        <div class="alertbox">
            <c:if test="${not empty param.info}">
                <div class="alert alert-success" role="alert">${param.info}</div>
            </c:if>

            <c:if test="${not empty param.error}">
                <div class="alert alert-danger" role="alert">${param.error}</div>
            </c:if>
        </div>
        <c:if test="${not empty list}">
            <ul class="mapping-list">
                <c:forEach items="${list}" var="item">
                    <li class="mapping-row">
                        <h4 data-toggle="tooltip" title="${status_title}"><c:choose>
                            <c:when test="${item.active}">
                                <span class="glyphicon glyphicon-ok-circle mapping_on" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Active"></span>
                            </c:when>
                            <c:otherwise>
                                <span class="glyphicon glyphicon-remove-circle mapping_off" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Inactive"></span>
                            </c:otherwise>
                        </c:choose> ${item.name}</h4>
                        <div class="set-box">
                            <div class="set">
                                <div class="field-name">TARGET</div>
                                <div class="field-value">
                                    <c:forEach items="${item.condition.rabbitIdSet}" var="rabbit" varStatus="stat">
                                        <a href="/log/list.err?id=${rabbit}">${rabbit}</a><c:if test="${not stat.last}">,</c:if>
                                    </c:forEach>
                                </div>
                            </div>
                            <div class="set set-border">
                                <div class="field-name">CONDITION</div>
                                <div class="field-value">
                                    <div class="element row">
                                        <span class="element-name col-md-3">level:</span>
                                        <span class="element-value col-md-3" data-toggle="tooltip" title="Threshold level"><u>${item.condition.matchLevel}</u></span>
                                        <span class="element-name col-md-3">class:</span>
                                        <span class="element-value col-md-3" data-toggle="tooltip" title="Matching class">
                                            <c:choose><c:when test="${not empty item.condition.matchClass}"><u>specific</u></c:when><c:otherwise>any</c:otherwise></c:choose>
                                        </span>
                                    </div>
                                    <div class="element row">
                                        <span class="element-name col-md-3">message:</span>
                                        <span class="element-value col-md-3" data-toggle="tooltip" title="Matching message contents">
                                            <c:choose><c:when test="${not empty item.condition.includeMessage}"><u>specific</u></c:when><c:otherwise>any</c:otherwise></c:choose>
                                        </span>
                                        <span class="element-name col-md-3">exception:</span>
                                        <span class="element-value col-md-3" data-toggle="tooltip" title="Is only exception">
                                            <c:choose><c:when test="${item.condition.hasException}"><u>yes</u></c:when><c:otherwise>any</c:otherwise></c:choose>
                                        </span>
                                    </div>
                                    <div class="element row">
                                        <span class="element-name col-md-3">threshold:</span>
                                        <span class="element-value col-md-3" data-toggle="tooltip" title="Threshold count during period">${item.condition.thresholdCount}</span>
                                        <span class="element-name col-md-3">period:</span>
                                        <span class="element-value col-md-3" data-toggle="tooltip" title="Period">${item.condition.periodSec}s</span>
                                    </div>
                                    <div class="element row">
                                        <span class="element-name col-md-3">sleep:</span>
                                        <span class="element-value col-md-3" data-toggle="tooltip" title="Sleep sec after action">${item.condition.sleepSecAfterAction}s</span>
                                    </div>
                                </div>
                            </div>
                            <div class="set set-border">
                                <div class="field-name">ACTIONS <a href="action?id=${item.id}" data-toggle="tooltip" data-placement="top" title="Modify actions"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a></div>
                                <div class="field-value">
                                    <c:forEach items="${item.actions}" var="action" varStatus="stat">
                                        <a href="/event/action/modify.err?id=${action.id}" data-toggle="tooltip" data-placement="right" title="${action.typeName}">${action.name}</a><c:if test="${not stat.last}">,</c:if>
                                    </c:forEach>
                                </div>
                            </div>
                        </div>
                        <a class="set set-button" href="modify.err?id=${item.id}" data-toggle="tooltip" data-placement="auto" title="Modify event mapping">
                            <span class="glyphicon glyphicon-menu-right" aria-hidden="true">&nbsp;</span>
                        </a>
                    </li>
                </c:forEach>
            </ul>
        </c:if>
    </div>
</section>
<jsp:include page="../common/footer.jsp"/>
</body>
</html>